-- MySQL Script generated by MySQL Workbench
-- Fri Oct 12 13:22:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `company` DEFAULT CHARACTER SET utf8 ;
USE `company` ;

-- -----------------------------------------------------
-- Table `company`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`worker` (
  `idworker` INT GENERATED ALWAYS AS () VIRTUAL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`idworker`),
  UNIQUE INDEX `idworker_UNIQUE` (`idworker` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`time` (
  `idtime` INT NOT NULL,
  `idworker` INT NOT NULL,
  `arrival` DATE NOT NULL,
  PRIMARY KEY (`idtime`),
  UNIQUE INDEX `idtime_UNIQUE` (`idtime` ASC),
  INDEX `idworker_idx` (`idworker` ASC),
  CONSTRAINT `idworker`
    FOREIGN KEY (`idworker`)
    REFERENCES `company`.`worker` (`idworker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`pay` (
  `idpay` INT NOT NULL,
  `rating` INT NOT NULL,
  `payout` INT NOT NULL,
  PRIMARY KEY (`idpay`),
  INDEX `rating_idx` (`rating` ASC),
  CONSTRAINT `rating`
    FOREIGN KEY (`rating`)
    REFERENCES `company`.`worker` (`idworker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`position` (
  `idposition` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idposition`),
  CONSTRAINT `idposition`
    FOREIGN KEY (`idposition`)
    REFERENCES `company`.`worker` (`idworker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`projects` (
  `idprojects` INT NOT NULL,
  `idworker` INT NOT NULL,
  `nameProject` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idprojects_UNIQUE` (`idprojects` ASC),
  INDEX `idworker_idx` (`idworker` ASC),
  CONSTRAINT `idworker`
    FOREIGN KEY (`idworker`)
    REFERENCES `company`.`worker` (`idworker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
